MAINTAINER_EMAIL: "maintainer@example.com"
POSTGRESQL_CKAN_PASSWORD: "SecretPostgresqlPassword"
CKAN_SITE_URL: "http://{{ inventory_hostname }}"
CKAN_STORAGE_PATH: "/data"

DCOR_USE_MINIO: true
DCOR_DEVELOP: true
DCOR_SITE_CONFIG_DIR: /dcor-repos/dcor_control/dcor_control/resources/site_dcor-dev
MINIO_ROOT_USER: minioadmin
MINIO_ROOT_PASSWORD: miniopassword

S3_ACCESS_KEY_ID: DCORMinIOAccessKeyId
S3_SECRET_ACCESS_KEY: DCORMinIOSecretAccessKey
