# These are secrets that only need to be known by the host, so we can set them
# to a random string.
- name: Create random postgresql password for ckan
  set_fact:
    cacheable: false
    POSTGRESQL_CKAN_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=64) }}"
- name: Create random CSRF key
  set_fact:
    cacheable: false
    CKAN_INI_WTF_CSRF_SECRET_KEY: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=64) }}"
- name: Create random MinIO root password
  when: DCOR_USE_LOCAL_MINIO | bool
  set_fact:
    cacheable: false
    MINIO_ROOT_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=64) }}"
- name: Create random MinIO access key id and secret
  when: DCOR_USE_LOCAL_MINIO | bool
  set_fact:
    cacheable: false
    DCOR_S3_SECRET_ACCESS_KEY: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits'], length=64) }}"
