- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: Only keep nginx logs for seven days
  block:
    - name: Install logrotate
      ansible.builtin.apt:
        name: logrotate
    - name: Create logrotate file for nginx logs
      ansible.builtin.template:
        src: etc_logrotate_nginx.j2
        dest: /etc/logrotate.d/nginx
        group: root
        owner: root
        mode: 0644
