CKAN_ENVIRONMENT_ACTIVATE: "/usr/lib/ckan/default/bin/activate"

DCOR_PUBLIC_DOMAIN: "{{ inventory_hostname }}"

CKAN_INI: "/etc/ckan/default/ckan.ini"
CKAN_INI_SITE_TITLE: "DCOR Base"
CKAN_INI_SOLR_URL: "http://localhost:8983/solr/ckan"
CKAN_INI_AUTH_CREATE_USER_VIA_API: false
CKAN_INI_AUTH_CREATE_USER_VIA_WEB: false

DCOR_SCRATCH_DIRECTORY: "/cache"
DCOR_DEVELOP: false
DCOR_USE_LOCAL_MINIO: false
# We set SSL verification to True, even though this won't work with MinIO,
# because it is a sane default.
DCOR_HTTPS_ENABLED: true

# Object storage access
DCOR_S3_ACCESS_KEY_ID: "dcor-access"
DCOR_S3_ENDPOINT_URL: "http://127.0.0.1:9000"
# The S3 bucket name stub is a unique prefix to the buckets created by DCOR.
# There might be multiple DCOR instances on one S3 instance, so it should be
# sufficiently unique.
DCOR_S3_BUCKET_NAME_STUB: "circle-{{ inventory_hostname }}"
# If we are using DCOR_USE_LOCAL_MINIO:
MINIO_ROOT_USER: "minioadmin"
MINIO_VOLUMES: "/srv/minio"

POSTGRESQL_CKAN_USER: "ckan_default"
POSTGRESQL_CKAN_DATABASE: "ckan_default"

# https://dl.min.io/server/minio/release/linux-amd64/archive/
MINIO_SERVER_VERSION: "20250422221226.0.0"
MINIO_SERVER_DEB_NAME: "minio_{{ MINIO_SERVER_VERSION }}_amd64.deb"
MINIO_SERVER_DEB_SHA256: "d8898351831761e083e7ba6b74ea7ec478b9a6680794fe92e5e838145341c9c5"

# https://dl.min.io/client/mc/release/linux-amd64/archive
MINIO_CLIENT_VERSION: "20250416181326.0.0"
MINIO_CLIENT_DEB_NAME: "mcli_{{ MINIO_CLIENT_VERSION }}_amd64.deb"
MINIO_CLIENT_DEB_SHA256: "e4e100c6cb5cb7087527602f9a618c60599da345834e497d66f41af18ce730f1"

ANSIBLE_DOWNLOAD_DIR: "/root/ansible_downloads/"
