CKAN_ENVIRONMENT_ACTIVATE: "/usr/lib/ckan/default/bin/activate"
CKAN_STORAGE_PATH: "/var/lib/ckan/default"
CKAN_INI_FILE: "/etc/ckan/default/ckan.ini"
CKAN_MAJOR_VERSION: "2"
CKAN_MINOR_VERSION: "2.11"
CKAN_PATCH_VERSION: "2.11.3"
CKAN_DEB_NAME: "python-ckan_{{ CKAN_MINOR_VERSION }}-{{ ansible_distribution_release }}_amd64.deb"
CKAN_DEB_MD5: "e8fcc52f89dccf311fbe902361becd40"


POSTGRESQL_CKAN_USER: "ckan_default"
POSTGRESQL_CKAN_DATABASE: "ckan_default"

SOLR_VERSION: "9.8.1"
SOLR_INSTALLER_SHA512: "08888ea626b9fa617438b97f9f8d552acfbd087fc9fd248e7495627716decca5e2e8d55bedf0e1f2484c838295c2abd68debb002d1ae36965eb99753320459f4"
